version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: dashboard_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: dashboard
    volumes:
      - mongodb_data:/data/db
    networks:
      - dashboard_network

volumes:
  mongodb_data:

networks:
  dashboard_network:
    driver: bridge
